### ISSUE TITLE
XMLSyntaxError: Space required after the Public Identifier, line 1, column 50

### ISSUE THREAD

**Issue by samba1979** [netvoip/cucm-phonegrabber#1]
Hi,

I'm getting an error when trying to run this, not sure why.  The path to the wsdl files is correct and verified.

Thanks

C:\Program Files\grabber>py get_phones_sn.py -name SEP*
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\zeep\loader.py", line 50, in parse_xml
    elementtree = fromstring(content, parser=parser, base_url=base_url)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\lxml\etree.pyx", line 3257, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1916, in lxml.etree._parseMemoryDocument
  File "src\lxml\parser.pxi", line 1803, in lxml.etree._parseDoc
  File "src\lxml\parser.pxi", line 1144, in lxml.etree._BaseParser._parseDoc
  File "src\lxml\parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 657, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Space required after the Public Identifier, line 1, column 50

**Comment by netvoip** [comment]
Probably you haven't configured path to WSDL schema file. Follow the instructions.
